### ISSUE TITLE
User details don't save + users cannot be deleted

### ISSUE THREAD

**Issue by rvtis** [opendcim/openDCIM#1309]
1. User names and surnames cannot be saved, no matter how many times I enter and press update. This affects department assigning and readability, since that function keeps saying that the user needs a name and surname.
2. Users can only be deactivated, not deleted, which is a privacy breach as it shows ex-employees and their full details.  There should be a Delete User button.

Employee details censored for privacy. Initials kept as an example.
![fgfdgfdgf](https://user-images.githubusercontent.com/47510851/178451489-db6ca274-89f9-4ff0-9a30-9bb70b04396b.png)

![liuoioiu](https://user-images.githubusercontent.com/47510851/178452044-ec6b7dff-56b9-4d1c-87e5-1a7541de16f9.png)

**Comment by samilliken** [comment]
You didn't specify enough details - what authentication method are you using?   Certain ones override anything you enter into those fields with what is sent, and that is by design.

Users can't be deleted because of the audit requirements.   If you remove the user information then the audit logs basically state that a ghost did the change.   Business records don't fall under the same privacy issues as collected customer data.

**Comment by rvtis** [comment]
Active Directory. How would that override anything, if their user ID was already pulled from AD, which has all the details? If Windows shows your full name upon login, surely DCIM should be able to pull that info from AD, right?

**Comment by samilliken** [comment]
You need to set up your Attribute Mapping.   That's what tells openDCIM which attributes contain the givenName, surname, mail, and phone fields.   It's also where you tell it what group memberships would determine rights (if you are using it for that).
